apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ .Values.route.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.route.path }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}