namespace:
  name: zano-ui

image:
  name: aks-app-ui-zano-press
  registry: zanoacrs2fckki4vwff2.azurecr.io
  #registry: localhost  # Use localhost for local development
  tag: latest
  imagePullPolicy: Always
  #imagePullPolicy: IfNotPresent  # Use IfNotPresent for local development

deployment:
  name: aks-app-ui-zano-press-deployment
  containerName: aks-app-ui-zano-press
  containerPort: 8080
  replicaCount: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "200m"
      memory: "64Mi"

service:
  name: aks-app-ui-zano-press-service
  type: ClusterIP # Change to LoadBalancer for AKS, ClusterIP for local dev
  #type: NodePort # Change to NodePort for local development with kind/, minikube but im using hostNetwork: true i
  targetPort: 8080 # The port your container listens on
  port: 3000 # The port your service will be exposed on
  #nodePort: 32000

secret:
  name: zano-tls-secret

gateway:
  name: zano-gateway
  namespace: zano-gateway # namespace of the shared aks-infra gateway

route:
  name: zano-http-route-zano-press
  host: zano-dev.westus.cloudapp.azure.com
  path: /zano-press
